### PR TITLE
Add Botanical Addons support

### LINKED ISSUE #301: [Request] Botanical Addons (Botania) support
The fancy new Dendric Suffuser. Sort of a hybrid of the Runic Altar and Thaumcraft's Infusion Altar.

Functionality:
https://www.youtube.com/watch?v=KlrQioZ9fN0&feature=youtu.be

Context:
https://www.reddit.com/r/botania/comments/43fouv/botanical_addons_botania_thaumcraft_aspects_sound/cziae2r?context=3

Github:
https://github.com/L0neKitsune/Botanical-Addons

### PR DESCRIPTION
**Pull request by yrsegal**
closes #301

### CODE REVIEW

**Comment by Voidi** [comment]
Nice!
But it seems you are a developer of Botanical Addons, so you could have Minetweaker Support IN Botanical Addons. Because support all these Mods in Modtweaker and have it up to date is a pain in the ass.

**Comment by yrsegal** [comment]
I can do that? oh. .-.

**Comment by yrsegal** [comment]
thanks, i'll implement this on our side.

**Comment by Voidi** [comment]
@yrsegal poke me if you need help with that.

**Comment by yrsegal** [comment]
After attempting to so this on BA's side, I realize just how easy your helper classes made it. Also, problems with Kotlin not liking ambiguous overloads mean I can't just have Modtweaker as a soft dep. I think the best solution is to implement it here.

**Comment by Voidi** [comment]
Ah Didn't know that you use kotlin, yes this make it bit more difficult. As a note you don't have to use Modtweaker as dependency, only Minetweaker is requiered.

Yes if you don't get it work in your mod, we will merge this.
But first a little request including an API as source files is actually not recommend.

Have Botanical Addons some kind specific API Jar or development version (is this what most mods as name deobfuscated.jar?)
If no than include the API as a git submodule.

**Comment by yrsegal** [comment]
Ok, i can supply a deobf .jar file easily enough.

**Comment by yrsegal** [comment]
ok, [newest version](http://minecraft.curseforge.com/projects/botanical-addons/files/2281022) has a deobf jar! I'll get to work using that instead.

**Comment by yrsegal** [comment]
All ready, and rebased into one commit for you.

**Pull request merged**
