### PR TITLE
Update for Forestry 4.0.3

### PR DESCRIPTION
**Pull request by AnodeCathode**
Mostly container/class renames.

### CODE REVIEW

**Comment by Voidi** [comment]
Thanks, will merging this after the Release of Forestry 4.0

**Comment by mezz** [comment]
Forestry 4 has been released

**Comment by Voidi** [comment]
Thanks @mezz 
@jaredlll08 a last modtweaker release for the old forestry version? To have a modtweaker version with the latest Zenscript Signature Changes?

**Comment by Voidi** [comment]
fixed with 4bea2e5fc92e59994303283c49c0326934d78163

**Pull request closed without merging**
