### PR TITLE
Swap mechanism sawmill input to be checked first before optional output

### PR DESCRIPTION
**Pull request by AnodeCathode**
Otherwise it finds no recipes to remove, ever.

### CODE REVIEW

**Comment by Yulife** [comment]
Is it working in your instance?

**Comment by Zixxl** [comment]
The order of the checks doesn't matter, if any of the checks fails, it won't alter the recipe.
If you don't provide the optional parameters, they will default to ```IngredientAny``` or ```<*>``` which always return true and the checks succeeds (won't skip the entry).
Maybe the Mekanism Sawmill also has the issue, that the recipes are loaded after modtweaker tries to apply the changes.
Can you provide the scripts you are using to remove the recipes?

**Comment by Zixxl** [comment]
Ah, i think i found the issue: #215
Already fixed in the repository, the fix will be released with 0.9.2

**Comment by AnodeCathode** [comment]
I'm really confused. It says invalid, but you've now swapped the Stackhelper check in Sawmill.java although I cannot determine when it was changed. It does make a difference because the StackHelper.matches command doesn't appear to support IngredientAny, unless I'm missing something.

**Pull request closed without merging**
