### PR TITLE
fix: add liquid to Forestry Carpenters internal tank filter, so new liquids are accepted

### PR DESCRIPTION
**Pull request by Voidi**
otherwise only liquids that forestry are aware, will work.

modified:   src/main/java/modtweaker/mods/forestry/handlers/Carpenter.java

### CODE REVIEW

**Comment by Yulife** [comment]
Thanks! But.. I never knew the Carpenter was limited to certain liquids.. (?)

**Comment by Yulife** [comment]
Seems like you broke the fluid handler for the Carpenter.
Using [this](http://puu.sh/f3yEj/9e98055fb9.txt) script I get [this](http://puu.sh/f3yR3/aba571dd8f.txt) error.

**Comment by Voidi** [comment]
The first link is not a script, its only the method.
I don't check if Fluid is null, maybe that's the error.

**Comment by Yulife** [comment]
Ooops! This is the script http://puu.sh/f3BYX/00126788c4.txt

**Comment by Voidi** [comment]
you use <minecraft:log:*> as crating box interessting ;)
I wasn't aware that Forestry changend things in the last days how crating/boxes was handled.

**Comment by Voidi** [comment]
which Forestry release do you use?

**Comment by Yulife** [comment]
439.

**Comment by Voidi** [comment]
ok as of this change the field with valid fluid is private
https://github.com/ForestryMC/ForestryMC/commit/c6dae0318c8d997f67435dbdeb34b5621563e2ef#diff-e88d04eb1991e5ddc75188cad77732df

what should we do?
use some amount of reflection (if possible) to change the list
ignore the list, so via script only origninal allowed fluids are psssible

**Comment by Yulife** [comment]
I am not a coder, you tell me :P

**Comment by Yulife** [comment]
By the way, come #jaredlll08 in espernet IRC.

**Pull request merged**
