### PR TITLE
add: Centrifuge, ThermiionicFabricator(Smelting & Casting) support

### PR DESCRIPTION
**Pull request by Voidi**
modified:   src/main/java/modtweaker/mods/forestry/Forestry.java
modified:   src/main/java/modtweaker/mods/forestry/handlers/Carpenter.java
new file:   src/main/java/modtweaker/mods/forestry/handlers/Centrifuge.java
new file:   src/main/java/modtweaker/mods/forestry/handlers/ThermionicFabricator.java

### CODE REVIEW

**Comment by Yulife** [comment]
[code]
test
[code/]

**Comment by Yulife** [comment]
Hey @Voidi how come [this](http://paste.ee/p/P1DUq) is not working?
It throws me an error called:
[22:54:01] [Client thread/INFO]: [CHAT] ERROR: forestry.zs:38 > a method available but none matches the parameters (int, any[], minetweaker.item.IItemStack)

**Comment by Yulife** [comment]
Also, what in the world does addCast and removeCasts do? Why is it a plural at "remove"? And why is there a "RemoveSmelting" duplicate that is just capitalized in the beginning? Same goes for "RemoveCastings". What do they do? lol

**Comment by InfinityRaider** [comment]
Looking at the code, the method is:
addCast(ILiquidStack fluidInput, IItemStack[][] ingredients, IItemStack plan, IItemStack product)

you're missing one ItemStack in the arguments

**Comment by Yulife** [comment]
Ah cheers, that .. worked. However, it gave me this [CTD](http://paste.ee/p/bqws4):

**Comment by Yulife** [comment]
Nope. That didn't work. I put a # infront of it so it wasn't even activated.
[00:22:40] [Client thread/INFO]: [CHAT] ERROR: forestry.zs:38 > a method available but none matches the parameters (int, minetweaker.item.IItemStack[][], minetweaker.item.IItemStack, minetweaker.item.IItemStack)
Still getting this error.

**Comment by Voidi** [comment]
What's your exact line of script?

regarding addCast, removeCastings:
The thermic. fabricator works in to steps: smelting and casting, very similar to the Smeltery from TConstruct.
So with addSmelting you can specify which Items are smeltable. (Since the internal Tank accept only glas, you do not have specify the output).
And then you can specify the casting with how much liquid glas and additional items, and an optional waxcast.
It is named removeCasts because you remove by naming the product, so all recipes which produce one item are removed.

**Comment by Yulife** [comment]
Ah... I see. However, I do think that "addRecipe" would be more sensible than "addCast", in my opinion. Could you also throw some example scripts in here because I have literally no idea how the executions work.

**Comment by jaredlll08** [comment]
If you need me in that chat, Please do @Jaredlll08.

**Comment by Voidi** [comment]
Centrifuge.addRecipe([Output, ...], [chance, ...], TimePerItem, Input);
#add: slimeball -> blaze_powder, magma_cream
Centrifuge.addRecipe([<minecraft:slime_ball>, <minecraft:blaze_powder>], [50, 100], 10, <minecraft:magma_cream>);

Centrifuge.removeRecipe(Input);
# remove Silky Propolis
Centrifuge.removeRecipe(<Forestry:propolis:3>);

#Smelting sometimes don't show correct in NEI
ThermionicFabricator.addSmelting(InputToSmelt, AmountOfLiquidGlass, Meltingpoint);
#AmountOfLiquidGlass, Meltingpoint are from type int
ThermionicFabricator.addSmelting(<minecraft:stone>, 1000, 1000);

ThermionicFabricator.removeSmelting(InputToSmelt);
ThermionicFabricator.removeSmelting(<minecraft:glass_pane>);

ThermionicFabricator.addCast(liquidStack liquidInput, ShapedRecipe, waxCast, Output);
#Shapedrecipe similar to normal Minetweaker syntax but you have to specify all slots
# set waxCast to null if you dont want to use one
#liquidInput can only be glass
ThermionicFabricator.addCast(<liquid:glass> * 1000, [[<minecraft:stick>, <minecraft:stick>, <minecraft:stick>], [null, null, null], [null, null, null]], <Forestry:waxCast:*>, <minecraft:minecart>);
ThermionicFabricator.addCast(<liquid:glass> * 1000, [[<minecraft:stick>, <minecraft:stick>, <minecraft:stick>], [null, null, null], [null, null, null]], null, <minecraft:minecart>);

ThermionicFabricator.removeCasts(InputToSmelt);
ThermionicFabricator.removeCasts(<Forestry:stained>);

**Comment by Yulife** [comment]
Github automatically removes <>. Would you mind pasting it? Also, cheers.

**Comment by Yulife** [comment]
Mhm, can you **only** use a block wax cast in the Fabricator or does it use the other wax casts as well? If it only accepts the block wax cast, make it to "true" for a wax cast in the recipe and "false" if it doesn't use the a wax cast respectively having a "null" in the script.

**Comment by Yulife** [comment]
And it should be "removeCast~~s~~" Adding a S will confuse people.

**Comment by Yulife** [comment]
Geez, I sound so evil, lol. Thanks for the hard work =]

**Comment by Voidi** [comment]
@Yulife nearly forgot to answer regarding waxcast:
the Fabricator accept only items of a special subclass
at the moment there is only one, but maybe someone want to add new ones for his pack (as i do)

**Comment by Yulife** [comment]
Alright!

**Comment by Yulife** [comment]
By the way, could you paste the script @Voidi?

**Comment by Voidi** [comment]
i don't have this testscript anymore, comeone whats your problem.

**Comment by Yulife** [comment]
I have no problem? It is just easier because Github removes  < and >.

**Pull request merged**
