### PR TITLE
Fixed deprecated method returns Character

### PR DESCRIPTION
**Pull request by miuirussia**

### CODE REVIEW

**Comment by Voidi** [comment]
What problem should fix this?

**Comment by miuirussia** [comment]
When using old scripts, it fails with casting error

**Comment by jaredlll08** [comment]
Still don't see the point for this

**Comment by jaredlll08** [comment]
There is no point for this, old scripts will fail because of changes anyway

**Comment by Voidi** [comment]
Yes they would fail without this fix

**Comment by jaredlll08** [comment]
They would fail because we have made changes to the params for scripts

**Pull request merged**
