### PR TITLE
Add basic support for TerraFirmaCraft

### PR DESCRIPTION
**Pull request by 3TUSK**
I did a rough test, and the function seems work. 
(New recipe can be shown in NEI correctly, with help of TFC-NEI Plugin)
Not sure if there is bug which hasn't been found.
If there is someone who can help me test, I will say appreciate. @Yulife

### CODE REVIEW

**Comment by Yulife** [comment]
That's quite impressive work, thanks a ton! Will test when I get home =) Does Oredict, Fuzzy Metadata and NBT-Data work with it?

**Comment by Yulife** [comment]
Also, is this everything doable with the TFC API? Iirc there were ovens and fireplaces as well. :)

**Comment by 3TUSK** [comment]
I haven't test fuzzy, nbt and oredict yet, but seems TFCraft API is using vanilla ItemStack. Not sure if oredict can be supported.
As for TFCraft forge and crucible, it seems impossible to add support. Currently I am thinking about adding support for knapping stone, clay and leather.

**Comment by 3TUSK** [comment]
Another thing, TFC API has a LoomManager and PlanManager, but loom requires a ResourceLocation, and PlanManager (which is for plan in an anvil) requires IIcon. (Which means that there must be already proper texture file somewhere.) 
I am not sure whether they are possible, but if possible I will start to work on them.

**Comment by Yulife** [comment]
That's unfortunate - and the campfire?

**Comment by 3TUSK** [comment]
Campfire has no related API file. I will double check whether there is possibility to add support after school.
Also, I found #43

**Comment by Yulife** [comment]
The campfire has no API integration...? Huh, I wonder how they do it,  can you clear this up @Kittychanley?  :) 

Thanks in advance ~

**Comment by 3TUSK** [comment]
Double checked again, seems I just ignore something... [HeatIndex]( https://github.com/Deadrik/TFCraft/blob/master/src/API/com/bioxx/tfc/api/HeatIndex.java )

**Comment by Yulife** [comment]
Oops, lol! Thanks ;)

**Comment by 3TUSK** [comment]
So far: 
I can make sure that quern, anvil, fogre/firepit are available.

Kiln is in a special situation, since a item which can be put into kiln must be a tfc ceramic thing.
(due to ```player.inventory.getCurrentItem().getItem() instanceof ItemPotteryBase```)

Loom haven't tested, since it requires a texture, and I'm bad at drawing :(

Barrel/Vessel are weird, new recipe can be shown in NEI (with TFC-NEIPlugin), but actually it doesn't work. I'll handle it.

**Comment by Yulife** [comment]
Tell me what you need, I'll draw you one :)

**Comment by 3TUSK** [comment]
Sorry, I found that I can just test custom loom recipe with the "missing texture" :)
Thank you for your support!

**Comment by joshiejack** [comment]
Did you try pullrequesting this to tfc/asking them if they would accept? (Since it's always better to be in the mod if possible)?

**Comment by 3TUSK** [comment]
Initial finished.
Due to the TFC API, ore-dict and fuzzy won't work well. NBT is supported, also many recipes in TFC are sensitive to NBT data.

Currently support: 
Anvil, Barrel/Vessel, Firepit/Forge, Quern
Currently support (not fully): 
Loom (sometimes missing texture, but it does work);
Kiln (recipe can be registered, but it requires that ```inputItem instanceof ItemPotteryBase```)

@joshiejack 
 [According to this,](https://github.com/Deadrik/TFCraft/issues/763 ) they might hope the support is part of ModTweaker2.

**Comment by joshiejack** [comment]
Ahh ok, that sucks then. Since as with all the other mods, it's another that will break when the mod updates, and then people come crying here xD

**Comment by Yulife** [comment]
What's the deal with "inputItem instanceof ItemPotteryBase"? Is it something special, does it need something special? Does it mean the items to it are limited? I'm confused - and by the way thanks for the hard work!

**Comment by jaredlll08** [comment]
It means that the return item must implement or extend that class.

**Comment by 3TUSK** [comment]
Which means it is a little complex work for a modpack creator. (They might need to create a new mod)

**Comment by Yulife** [comment]
Oh. Couldn't this be done in a TFC helper in Modtweaker itself?

**Comment by 3TUSK** [comment]
@Yulife I don't think so...

**Comment by Yulife** [comment]
@jaredlll08 is doing a lot of helpers, you think it will work?

**Comment by Yulife** [comment]
@3TUSK Want me to merge?

**Comment by 3TUSK** [comment]
@Yulife If there is no known bug... XD

**Comment by jaredlll08** [comment]
If you can confirm no bugs. i will merge and release the mod

**Comment by 3TUSK** [comment]
Give me sometime...

**Comment by 3TUSK** [comment]
Double checked, and I believe there is no bugs.

**Comment by Yulife** [comment]
yay2
Thank you!! ~~ :+1: :+1: :+1:

**Comment by Yulife** [comment]
Alright going through the handlers right now... what I noticed:

1: You can [use](http://gyazo.com/354e4b1c6e6501f351d293c4f4160db4) null two in the anvil and it works. This should at least throw an error if you use null in the script two times. 

2: As you can see in the picture I used "iamnotaplan" for the plan string. This does not throw an error which is worrisom. It should throw an error if the string is not precisely correct.

**Comment by 3TUSK** [comment]
Y'all are very welcome XD

**Comment by Yulife** [comment]
And what's "int value" in the anvil handler? I can figure out all different things but "value" leaves me confused.

**Comment by 3TUSK** [comment]
Ahhhh, anvil is a thing...
1.is there anyone who really add a anvil recipe with two null input? But I will consider to throw error under such a situation.
2.As for plan, there are some existed plan inside of the TFC source code...

**Comment by jaredlll08** [comment]
Just an integer, a field with the value if an int

**Comment by Yulife** [comment]
Ahhh, thanks @3TUSK!
1: Yeah, it would make sense. No one would enter two inputs.
2: Yes, I know, I am going to list them on the documentation. However, if someone makes a typo, it would be neat if an error would be thrown. For example, the string "oillamp" in TFC. If I were to be in a hurry and write "oilamp" it would be **very** helpful if an error would be thrown instead of scavenging through the code for hours to find out why it doesn't work.

@jaredlll08 that doesn't clear anything up. I mean what it actually has in relation to TFC, for example "int req" is the Tier of anvil to be used for the recipe. What does value do?

**Comment by 3TUSK** [comment]
If my memory is accurate, the int-type parameter "value" means the "crafting progress".
[Click it to learn more. (check Anvil GUI 8.)] (http://wiki.terrafirmacraft.com/Anvil)

**Comment by jaredlll08** [comment]
uh.. I just tried opening my dev environment... it crashes with TFC...

**Comment by 3TUSK** [comment]
what... I am using TFC 0.79.17, Forge 10.13.2.1291

**Comment by jaredlll08** [comment]
Exactly the same stuff here... foes TFC need any other mods?

**Comment by Yulife** [comment]
Huh, interesting. However, I am not sure what number to put in there, lol. *Confused :s*

**Comment by 3TUSK** [comment]
TFC doesn't require a dependency... Also Iam  using NEI 1.0.4.83, waila 1.5.8a
Other mods: buildcraft 7.0.1, ic2exp 2.2.717, fastcraft-1.19, minetweaker 3.0.9C

**Comment by jaredlll08** [comment]
well I just tried loading it up with all other modtweaker mods
and it is giving this error:
http://www.blamejared.com/GetFluxed/content/2015-04-19_17-52-37.txt

**Comment by 3TUSK** [comment]
It looks like TFC's fault.
did you download TFC from http://terrafirmacraft.com/download.html ?

**Comment by 3TUSK** [comment]
https://github.com/Deadrik/TFCraft/blob/master/src/Resources/META-INF/tfc_at.cfg

**Comment by jaredlll08** [comment]
probably...

**Pull request merged**
